domain_path: D:\Vivado\Learning\Vitis\Learning_1\msc_project_platform\export\msc_project_platform\sw\RTOS
app_src_dir: D:\Vivado\Software\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
