
#ifndef NET_ENGINE_HW_H
#define NET_ENGINE_HW_H


/****************** Include Files ********************/


/******************* Registers ********************/

#define NET_ENGINE_S00_AXI_SLV_REG0_OFFSET 0
#define NET_ENGINE_S00_AXI_SLV_REG1_OFFSET 4
#define NET_ENGINE_S00_AXI_SLV_REG2_OFFSET 8
#define NET_ENGINE_S00_AXI_SLV_REG3_OFFSET 12
#define NET_ENGINE_S00_AXI_SLV_REG4_OFFSET 16
#define NET_ENGINE_S00_AXI_SLV_REG5_OFFSET 20
#define NET_ENGINE_S00_AXI_SLV_REG6_OFFSET 24
#define NET_ENGINE_S00_AXI_SLV_REG7_OFFSET 28
#define NET_ENGINE_S00_AXI_SLV_REG8_OFFSET 32
#define NET_ENGINE_S00_AXI_SLV_REG9_OFFSET 36
#define NET_ENGINE_S00_AXI_SLV_REG10_OFFSET 40
#define NET_ENGINE_S00_AXI_SLV_REG11_OFFSET 44
#define NET_ENGINE_S00_AXI_SLV_REG12_OFFSET 48
#define NET_ENGINE_S00_AXI_SLV_REG13_OFFSET 52
#define NET_ENGINE_S00_AXI_SLV_REG14_OFFSET 56
#define NET_ENGINE_S00_AXI_SLV_REG15_OFFSET 60
#define NET_ENGINE_S00_AXI_SLV_REG16_OFFSET 64
#define NET_ENGINE_S00_AXI_SLV_REG17_OFFSET 68
#define NET_ENGINE_S00_AXI_SLV_REG18_OFFSET 72
#define NET_ENGINE_S00_AXI_SLV_REG19_OFFSET 76

// Status Registers
#define NET_ENGINE_STATUS_REG_1 NET_ENGINE_S00_AXI_SLV_REG0_OFFSET
#define NET_ENGINE_STATUS_REG_2 NET_ENGINE_S00_AXI_SLV_REG1_OFFSET
#define NET_ENGINE_STATUS_REG_3 NET_ENGINE_S00_AXI_SLV_REG2_OFFSET
#define NET_ENGINE_STATUS_REG_4 NET_ENGINE_S00_AXI_SLV_REG3_OFFSET
#define NET_ENGINE_STATUS_REG_5 NET_ENGINE_S00_AXI_SLV_REG4_OFFSET
#define NET_ENGINE_STATUS_REG_6 NET_ENGINE_S00_AXI_SLV_REG5_OFFSET 
// Configuration Registers
#define NET_ENGINE_CONFIG_REG_1 NET_ENGINE_S00_AXI_SLV_REG6_OFFSET 
#define NET_ENGINE_CONFIG_REG_2 NET_ENGINE_S00_AXI_SLV_REG7_OFFSET 
#define NET_ENGINE_CONFIG_REG_3 NET_ENGINE_S00_AXI_SLV_REG8_OFFSET 
#define NET_ENGINE_CONFIG_REG_4 NET_ENGINE_S00_AXI_SLV_REG9_OFFSET 
// Kernal and Bias Registers
#define NET_ENGINE_BIAS_REG     NET_ENGINE_S00_AXI_SLV_REG10_OFFSET 
#define NET_ENGINE_KERNAL_REG_1 NET_ENGINE_S00_AXI_SLV_REG11_OFFSET 
#define NET_ENGINE_KERNAL_REG_2 NET_ENGINE_S00_AXI_SLV_REG12_OFFSET 
#define NET_ENGINE_KERNAL_REG_3 NET_ENGINE_S00_AXI_SLV_REG13_OFFSET 
#define NET_ENGINE_KERNAL_REG_4 NET_ENGINE_S00_AXI_SLV_REG14_OFFSET 
#define NET_ENGINE_KERNAL_REG_5 NET_ENGINE_S00_AXI_SLV_REG15_OFFSET 
#define NET_ENGINE_KERNAL_REG_6 NET_ENGINE_S00_AXI_SLV_REG16_OFFSET 
#define NET_ENGINE_KERNAL_REG_7 NET_ENGINE_S00_AXI_SLV_REG17_OFFSET 
#define NET_ENGINE_KERNAL_REG_8 NET_ENGINE_S00_AXI_SLV_REG18_OFFSET 
#define NET_ENGINE_KERNAL_REG_9 NET_ENGINE_S00_AXI_SLV_REG19_OFFSET 


/**************************** Type Definitions *****************************/

#endif // NET_ENGINE_HW_H
